### PR TITLE
add limit=10 for plotting while training

### PR DESCRIPTION
**Pull request by Laughing-q**
add limit=10 for plotting while training to save memory and speed up

### CODE REVIEW

**Comment by AyushExel** [comment]
@Laughing-q looks good! I haven't taken a closer look but does this limit both detection and masks or just the masks?
I think what we should do here is this:
* Sort the prediction based on confidence and then keep only top 10 predictions( boxes and masks)

**Comment by Laughing-q** [comment]
@AyushExel yes it works with both bboxes and masks. But I didn't do sorting, I think it's better to add sorting in `non_max_suppression_masks` for the current code structure. I'll add sorting tomorrow and test it, then update the PR.

**Comment by AyushExel** [comment]
@Laughing-q cool that sounds good! Let me know whenever its ready to merge

**Comment by Laughing-q** [comment]
@AyushExel hey, I already added object sorting in mask_nms, also I found a bug when I finished training and fixed it.

**Comment by AyushExel** [comment]
@Laughing-q awesome. I'll merge this and try to train again with plot=True and mask-ratio 1 on A100..hopefully it doesn't freeze the system

**Comment by AyushExel** [comment]
@Laughing-q you can see the live training here ->  https://wandb.ai/cayush/YOLOv5-Inst-seg/runs/1aicpjeu

**Pull request merged**
